version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - XAI_API_KEY=${XAI_API_KEY}
    volumes:
      - ./backend/src:/app
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend